In [11]:
import sys
from pathlib import Path

project_root = Path.cwd().parent
sys.path.append(str(project_root / "src"))

In [12]:
from quantts.data import download_market_data, save_raw_data

In [13]:
spy = download_market_data(
    ticker="SPY",
    start="2010-01-01"
)

spy.head()

,Adj Close,Close,High,Low,Open,Volume
Date,,,,,,
2010-01-04,84.578484,113.330002,113.389999,111.510002,112.370003,118944600
2010-01-05,84.802368,113.629997,113.680000,112.849998,113.260002,111579900
2010-01-06,84.862068,113.709999,113.989998,113.430000,113.519997,116074400
2010-01-07,85.220306,114.190002,114.330002,113.180000,113.500000,131091100
2010-01-08,85.503891,114.570000,114.620003,113.660004,113.889999,126402800

In [14]:
spy.tail()

,Adj Close,Close,High,Low,Open,Volume
Date,,,,,,
2026-09-03,773.169983,773.169983,774.030029,767.450012,767.900024,43531600
2026-09-04,770.190002,770.190002,772.869995,769.000000,772.010010,34054200
2026-09-08,765.960022,765.960022,769.700012,765.140015,769.070007,44746100
2026-09-09,762.400024,762.400024,764.469971,760.940002,764.080017,32812400
2026-09-10,757.830017,757.830017,760.109985,756.640015,758.030029,42679700

In [15]:
spy.shape

(4197, 6)

In [16]:
spy.columns

Index(['Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='str')

In [17]:
spy.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 4197 entries, 2010-01-04 to 2026-09-10
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Adj Close  4197 non-null   float64
 1   Close      4197 non-null   float64
 2   High       4197 non-null   float64
 3   Low        4197 non-null   float64
 4   Open       4197 non-null   float64
 5   Volume     4197 non-null   int64
dtypes: float64(5), int64(1)
memory usage: 229.5 KB

In [18]:
spy.isna().sum()

Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

In [19]:
save_raw_data(spy,"SPY")

WindowsPath('data/raw/spy_daily.csv')